### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/hps-users#17]
Been receiving security alerts to the JeffersonLab github organization on this repo regarding com.itextpdf:itext7-core for a while.   Need to update to a newer version.

![Screen Shot 2023-01-17 at 6 06 13 PM](https://user-images.githubusercontent.com/6279258/213031768-12ca5aad-7bcc-4334-8585-17c8e6bbe308.png)

**Comment by mholtrop** [comment]
See pull request https://github.com/JeffersonLab/hps-users/pull/18

It fixes the security vulnerability but breaks 2 of Norman's utilities.

**Comment by normangraf** [comment]
Thanks Maurik, I'll look into fixing my code.
